### PR TITLE
Excel Export Feature

### PR DESCRIPTION
**Pull request by crispmark**
Changes:

- Added button to download and excel export of search results
- Added a utility to generate an aggregator query string from a query and aggregator object
- Added tests for said utility

*Attention*: This button does not work by default when running the project on port 3001, as routes do not seem to be remapped to port 3000. I have not found how this is done, but it might be a good idea to incorporate express-http-proxy rather than routing everything through the client utility to avoid these kinds of issues. However I am open to any suggestion of how you would like this to work.

Update: process.env.API_HOST can be used at the root of the export url, and this would solve any problems.

### CODE REVIEW

**Comment by crispmark** [comment]
process.env.API_HOST can be used in place of /api/ for the export url, and this would fix any issues

**Review by relwell — CHANGES_REQUESTED** [review]
This looks good, but I think a POST request is more appropriate here given how complex our query interface is. 

I don't see how you're handling sorts here, which would make testing the integrity of Excel exports difficult.

**Comment by relwell** [comment]
One more thing to note -- if you assign me as a reviewer to pull requests, I'll see these changes sooner and can provide more timely feedback.

**Comment by williamhoos** [comment]
Also, not sure sorts need to persist to excel if it is easier to leave off.
Filters are needed.

**Pull request closed without merging**
